services:
  postgres:
    image: postgres:15
    container_name: blinkr_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - blinkr_postgres_data:/var/lib/postgresql/data    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: blinkr_pgadmin
    restart: always
    platform: linux/amd64
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:7
    container_name: blinkr_redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - blinkr_redis_data:/data

  eventstore.db:
    image: eventstore/eventstore:24.2.0-bookworm-slim
    container_name: blinkr_eventstore
    environment:
      - EVENTSTORE_INSECURE=True
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_LOG_LEVEL=Information
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=True
      - EVENTSTORE_GOSSIP_ON_SINGLE_NODE=True
      - EVENTSTORE_MEM_DB=True
    ports:
      - "2113:2113"
    volumes:
      - blinkr_eventstore_data:/var/lib/eventstore
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:2113/health/live || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  rabbitmq:
    image: rabbitmq:3-management
    container_name: blinkr_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo:6.0.2
    container_name: blinkr_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - blinkr_mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: blinkr_mongo_express
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    depends_on:
      - mongodb
    ports:
      - "8081:8081"

volumes:
  blinkr_postgres_data:
  blinkr_eventstore_data:
  blinkr_mongo_data:
  blinkr_redis_data:
