<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<!-- Versiyonlar Directory.Packages.props dosyasından yönetiliyor -->
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="MassTransit.RabbitMQ" />
		<PackageReference Include="MassTransit.EntityFrameworkCore" />
		<PackageReference Include="EventStore.Client.Grpc.Streams" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BlogService.Application\BlogService.Application.csproj" />
		<ProjectReference Include="..\BlogService.Domain\BlogService.Domain.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\Shared.Events\Shared.Events.csproj" />
	</ItemGroup>

</Project>
