<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Shared.Events\Shared.Events.csproj" />
    <ProjectReference Include="..\BlogService.Domain\BlogService.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="FluentValidation.AspNetCore" />
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="MongoDB.Bson" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="NetTopologySuite" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Models\" />
    <Folder Include="Features\Mediatr\Results\PostResults\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="DTOs\PostCommentDtos\PostCommentDto.cs" />
  </ItemGroup>

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
